name: Szabó Kristóf 
title: Kristóf Portfóliója  
descreption: Kristóf készítette 

markdown: kramdown

source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"

plugins:
  - jekyll-remote-theme


show_downloads: true