name: Szabó Kristóf 
title: Kristóf Portfóliója  
descreption: Kristóf készítette 

markdown: kramdown



baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

show_downloads: true